### ISSUE TITLE
Mistake in demonstration notebook

### ISSUE THREAD

**Issue by robintw** [haoliangyu/pymasker#2]
Just noticed that one of the code examples at http://haoliangyu.github.io/2015/01/18/Making-masks-with-Landsat-8-Quality-Assessment-band-using-Python/ is incorrect (or possibly just out-of-date).

The final code block uses the `getmask` function - but that seems to extra raw bit values, and actually the function that is used to extract multiple masks seems to be called `getmultimask`.

**Comment by haoliangyu** [comment]
@robintw There is indeed a mistake. Thanks for pointing out.

**Comment by haoliangyu** [comment]
Code example updated
