### ISSUE TITLE
Not working with collection-1 Landsat-8 data

### ISSUE THREAD

**Issue by lvhengani** [haoliangyu/pymasker#5]
Hi, 

Firstly let me thank you for this tool. I would like to know if you have any plans of updating it so that its able to work with Landsat-8 collection-1 data.

Regards,
Lufuno

**Comment by haoliangyu** [comment]
Sorry to response late.

I am not aware of the data release until now. I will take a look at the data format and see how to add support to it.

**Comment by lvhengani** [comment]
Thank you for your response. 
Do you perhaps know when will you be able to release the update?

**Comment by haoliangyu** [comment]
@lvhengani It looks like a urgent need for you. I will work on it tonight and hopefully publish it in one or two days.

**Comment by haoliangyu** [comment]
@lvhengani I am able to create a PR #6 for the landsat collection-1 data. I will run more tests in the next two days.

**Comment by lvhengani** [comment]
Thanks, I really appreciate. A new version that works with both pre-collection and collection-1 in the next two days will really be great.

**Comment by haoliangyu** [comment]
So the code is done, but the Python module publication procedure is changed again :-( Need to take time to learn again.

**Comment by lvhengani** [comment]
@haoliangyu thank you. I checked readme file. Its straight forward to specify collection when running via command line. How does one specify the collection when importing the class in a python script?
I would like to contribute to this project by creating a docker for running pymasker.

**Comment by haoliangyu** [comment]
Thanks for catching that. I forgot to update the doc for landsat.

Now the user need to specify the number for landsat.

**Python**

``` python
# load the QA band directly
#
# The "collection" parameter is required for landsat to specify the collection
# number. Acceptable number: 0 (pre-collection), 1 (collection-1)
#
masker = LandsatMasker('LC80170302014272LGN00_BQA.TIF', collection=0)
```

**CLI**

``` 
-C, --collection  LANDSAT COLLECTION NUMBER
  collection number of input image: 0 (pre-collection), 1
```

@lvhengani The library should be published before Monday :-)

**Comment by haoliangyu** [comment]
[v0.4.0](https://pypi.python.org/pypi/pymasker/0.4.0) is published :tada: 

@lvhengani Please continue to submit issue if you still have problem using this library. I have not tested its compatibility with Python 3, so please use 2.7 if possible.

**Comment by lvhengani** [comment]
Thank you @haoliangyu. I installed the new version using pip, tested it and its working. Much apprecaited.
