### ISSUE TITLE
Multimask

### ISSUE THREAD

**Issue by roemelll** [haoliangyu/pymasker#7]
Hello, 
thank you very much for this nice tool! I'm new to Python, but I managed to get seperate medium and high confidence cloud masks.
I would like to get a raster combining both medium and high confidence pixels. 

`mask = masker.get_multi_mask(cloud = LandsatConfidence.high, cloud = LandsatConfidence.medium)`

This command gives the following ERROR:

SyntaxError: keyword argument repeated

Is it possible to do what I aim for? 

Thank you, 

Roman

**Comment by lvhengani** [comment]
Hi Roman,
If I understand the BAQ file and pymasker properly, medium confidence mask should have high confidence clouds in it. I think it works this way:
1 High confidence mask will have only those clouds that statistically there is no doubt that they are clouds
2 Medium confidence mask should have high confidence clouds also with those clouds that statistically the propability that they are clouds is medium
3 Low confidence mask should have both high and medium clouds with those clouds that statistically the probalibity of them to be clouds is low.

**Comment by haoliangyu** [comment]
@roemelll If you are already successful to create medium confidence and high confidence cloud mask separately, I would recommend to do a `or` operation for two masks. The mask is just a two-dimension numpy array of 1 and 0. [numpy.bitwise_or](https://docs.scipy.org/doc/numpy/reference/generated/numpy.bitwise_or.html#numpy.bitwise_or) can be helpful in this case. The function `get_multi_mask` is not very well designed so I drop it at the current version of pymasker. If that function is still very useful to you, please let me know.

@lvhengani You are right when the `cumulative` option for the mask generation function is explicitly set as `True`. Currently, this options is `False` by default so the mask generated with no extra `cumulative` setting will be strictly representing the input confidence. The original masking value used in the BAQ band represent the state distinctly, or accumulative.  See the BAQ band documentation for [pre-collection](https://landsat.usgs.gov/qualityband) and [collection-1](https://landsat.usgs.gov/collectionqualityband) for more details.

**Comment by lvhengani** [comment]
@haoliangyu thank you for clarity, I have been running with `cumulative = True`. This makes sense to me than to do another process for merging the two.
