### ISSUE TITLE
Gdal Issue 

### ISSUE THREAD

**Issue by domierosina** [haoliangyu/pymasker#9]
Attempting to run  this in a juypter notebook and it seems there is an error with gdal within pymasker's build. This problem could be isolated to my computer, but I have done a fresh and the same result occurs. 

`ModuleNotFoundError: No module named 'gdal' `

Any help you could give would be great, thank you so much!

**Comment by lvhengani** [comment]
It seems like you need to install gdal on your computer.

**Comment by domierosina** [comment]
I do have it installed. I am able to call the instance of Gdal installed on my computer. The full error message is below. 
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-28-619e5d10ef79> in <module>
      1 # Need to load in the QA band and specify the collection (0, 1, 2)
----> 2 masker = LandsatMasker('E:\SummerC1L1_2015\LC08_L1TP_031022_20150817_20170226_01_T1\LC08_L1TP_031022_20150817_20170226_01_T1_BQA.TIF', collection=1)
      3 
      4 # Assign a confidence to the algorithm.
      5 conf = LandsatConfidence.high

~\anaconda3\lib\site-packages\pymasker.py in __init__(self, file_path, **var)
    122 
    123         self.collection = var['collection']
--> 124         super(LandsatMasker, self).__init__(file_path)
    125 
    126     def get_no_cloud_mask(self):

~\anaconda3\lib\site-packages\pymasker.py in __init__(self, band, **var)
     12                 self.load_file(band, var['band_num'])
     13             else:
---> 14                 self.load_file(band)
     15         else:
     16             self.load_data(band)

~\anaconda3\lib\site-packages\pymasker.py in load_file(self, file_path, band_num)
     23             band_num    -       Number of band.
     24         '''
---> 25         import gdal
     26 
     27         self.file_path = file_path

ModuleNotFoundError: No module named 'gdal'

**Comment by domierosina** [comment]
Answer to this issue, with any GDAL version newer than 3.1 the import of gdal is different that what is in this script. So in order to use this script as is, gdal must be 3.1 or older.
